apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: secrets-manager
            namespace: cp4i
            key: apiKey
      serviceUrl: >-
        https://1bd5aac8-f980-4fa8-8a60-6b3f5c62598c.au-syd.secrets-manager.appdomain.cloud
