apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-entitlement-key
  namespace: cp4i
spec: 
  data:
  - secretKey: ibmEntitlementKey
    remoteRef: 2b61a583-db5a-1dad-e55d-8480f823dc88
      key: 
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ibm-entitlement-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ .ibmEntitlementKey | toString }}