apiVersion: batch/v1
kind: Job
metadata:
  name: cp4x-verify-integration
  namespace: verify
spec:
  template:
    spec:
      serviceAccountName: cp4x-verify-sa
      containers:
      - name: configure-cp4x-verify
        image: quay.io/langley_millard_ibm/cp4x-verify
        command: ["./cp4x-verify.sh"]
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2
