kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-marketplace

bases:
  - ../../base

patches:
  # templatise images in catalog sources - v22.1
  # catalog source
  - target:
      kind: CatalogSource
      name: ibm-operator-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: 'icr.io/cpopen/ibm-operator-catalog:latest'

  